### PR TITLE
Added button sizes

### PR DESCRIPTION
**Pull request by nabadev**
I have added the **button sizes** for issue #5 :

- Primary Buttons
- Secondary Buttons
- CTA Buttons

Here is a **Codepan** for testing:- https://codepen.io/nabadev/details/VwEavpm

### CODE REVIEW

**Comment by CGWebDev2003** [comment]
Why did you make the sizes for each button class separately? Since they are all the same anyway due to the design system, you can also put them on `button`. You save code.

**Comment by nabadev** [comment]
Okay, I will try to improve it.

**Comment by nabadev** [comment]
>you can also put them on `button`

Can you please explain this?

**Comment by CGWebDev2003** [comment]
I mean you can set the sizes global for every button if you use the selector `button`

**Comment by nabadev** [comment]
Okay, Got it ;)

**Comment by CGWebDev2003** [comment]
OK Please make a new pull request

**Comment by nabadev** [comment]
Okay

**Pull request closed without merging**
